### PR TITLE
Committed to passion: Noel Jacob

### PR DESCRIPTION
**Pull request by NoelJacob**

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Remember to make the commit message something like "Committed to passion: Firstname Lastname".

**Comment by NoelJacob** [comment]
Committed to passion: Noel Jacob

with passion,
Noel Jacob

**Comment by BenWiederhake** [comment]
What you did was creating a new comment.

I'm asking to *change the commit message* to something more reasonable than just "Update README.md", because that's a really bad commit message, even for a small toy-project like this.

**Comment by NoelJacob** [comment]
Thank you

**Pull request merged**
